"""Initial migration

Revision ID: bcf573983211
Revises: 'None'
Create Date: 2026-08-06 12:00:50.482027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = 'bcf573983211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_opportunities',
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_infrastructure', sa.Text(), nullable=True),
    sa.Column('min_investment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_investment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_investment_scale', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_business_opportunities_sector'), 'business_opportunities', ['sector'], unique=False)
    op.create_table('municipalities',
    sa.Column('municipality_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=245), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=False),
    sa.Column('province', sa.String(length=250), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('municipality_id')
    )
    op.create_index(op.f('ix_municipalities_district'), 'municipalities', ['district'], unique=False)
    op.create_index(op.f('ix_municipalities_name'), 'municipalities', ['name'], unique=False)
    op.create_index(op.f('ix_municipalities_province'), 'municipalities', ['province'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MUNICIPAL_OFFICIAL', 'CITIZEN', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('municipality_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('suitability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('suitability_score BETWEEN 0 AND 100', name='chk_suitability_score_range'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.municipality_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['business_opportunities.opportunity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id'),
    sa.UniqueConstraint('municipality_id', 'opportunity_id', 'model_version', name='uq_muni_opp_model_version')
    )
    op.create_index(op.f('ix_ai_recommendations_municipality_id'), 'ai_recommendations', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_opportunity_id'), 'ai_recommendations', ['opportunity_id'], unique=False)
    op.create_table('resource_data',
    sa.Column('data_id', sa.String(length=36), nullable=False),
    sa.Column('municipality_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('indicator_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.municipality_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('municipality_id', 'category', 'indicator_name', 'year', name='uq_resource_data_muni_cat_ind_year')
    )
    op.create_table('saved_recommendations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_recommendations')
    op.drop_table('resource_data')
    op.drop_index(op.f('ix_ai_recommendations_opportunity_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_municipality_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_municipalities_province'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_name'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_district'), table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_index(op.f('ix_business_opportunities_sector'), table_name='business_opportunities')
    op.drop_table('business_opportunities')
    # ### end Alembic commands ###